trigger:
- main  

pool:
  name: default

stages:
  - stage: buildV
    jobs:
      - job: UsePython
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.10'

  - stage: build
    jobs:
      - job: build
        steps:
          # Install Dependencies with Admin Privileges
          - script: |
              powershell Start-Process npm -ArgumentList 'install' -Verb runAs
            displayName: 'Install Dependencies with Admin Privileges'

          # Build Application
          - script: |
              npm run build --prefix C:\agents2\vsts-agent-win-x64-4.248.0\app
            displayName: 'Build Application'
