trigger:
- main  

pool:
  name: default3PC

stages:
  - stage: setupPython
    displayName: "Setup Python Environment"
    jobs:
      - job: setup
        displayName: "Install Python and Dependencies"
        steps:
          # Instalar Python 3.10 si no está disponible
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe -OutFile python-installer.exe
                Start-Process python-installer.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait
                python --version
            displayName: 'Install Python 3.10'

          # Instalar dependencias con pip
          - script: |
              python -m ensurepip
              python -m pip install --upgrade pip
              pip install -r C:\agents2\vsts-agent-win-x64-4.248.0
            displayName: 'Install Python Dependencies'

  - stage: build
    displayName: "Run Python Application"
    jobs:
      - job: build
        displayName: "Execute Application"
        steps:
          # Ejecutar la aplicación Python
          - script: |
              python C:\agents2\vsts-agent-win-x64-4.248.0\main.py
            displayName: 'Run Python Application'
