trigger:
- main  # This ensures the pipeline runs only when changes are pushed to the 'main' branch.

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'  # Choose the appropriate Python version
    addToPath: true

- script: |
    pip install -r requirements.txt  # Install dependencies from requirements.txt
  displayName: 'Install Dependencies'

- script: |
    uvicorn main:app --host 0.0.0.0 --port 8080  # Replace 'main' with your FastAPI app file
  displayName: 'Run FastAPI locally (for testing)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publish Artifacts'
