trigger:
- main  

pool:
  name: default3PC

stages:
  - stage: setupPython
    displayName: "Download and Install Python"
    jobs:
      - job: installPython
        displayName: "Install Python 3.10"
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe -OutFile python-installer.exe
                Start-Process python-installer.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait
            displayName: 'Download and Install Python 3.10'


  - stage: build
    displayName: "Build Application"
    jobs:
      - job: build
        displayName: "Build and Install Dependencies"
        steps:
          # Verifica que npm está disponible
          - script: |
              echo Checking npm version...
              npm --version
            displayName: 'Verify npm Installation'

          # Install Dependencies with Admin Privileges
          - script: |
              powershell Start-Process npm -ArgumentList 'install' -Verb runAs
            displayName: 'Install Dependencies with Admin Privileges'

          # Build Application
          - script: npm prefix C:\agents2\vsts-agent-win-x64-4.248.0\app run build
            displayName: 'Build Application'
