name: FastAPI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run FastAPI locally (for testing)
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8080

      # Subir artefactos con la versión v3 de upload-artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v3  # Usar la versión correcta
        with:
          name: fastapi-artifacts
          path: ./  # Ruta a los artefactos generados
