name: FastAPI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Verify Python version
        run: python --version

      - name: List directory contents
        run: |
          ls -la
          cat requirements.txt  # Verifica si el archivo existe y tiene el contenido correcto

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run FastAPI locally (for testing)
        run: |
          ls -la  # Asegúrate de que los archivos están presentes
          uvicorn app.main:app --host 0.0.0.0 --port 8080  # Cambiado para usar el directorio 'app'

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fastapi-artifacts
          path: ./  # Ruta a los artefactos generados
