name: FastAPI CI/CD

on:
  push:
    branches:
      - main  # Este pipeline se ejecuta cuando haya un push en la rama main

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliza la última versión de Ubuntu como ambiente de ejecución

    steps:
    - name: Check out repository
      uses: actions/checkout@v2  # Revisa el código del repositorio en la VM de GitHub Actions

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # Asegúrate de que la versión sea 3.10 y no 3.1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Instala las dependencias del proyecto

    - name: Run tests
      run: |
        pytest  # Ejecuta los tests (asegúrate de que pytest esté instalado en tu requirements.txt)

    - name: Publish artifacts
      uses: actions/upload-artifact@v3  # Publica el artefacto con la versión correcta de upload-artifact
      with:
        name: fastapi-artifacts
        path: .  # Publica el directorio actual como artefacto
