name: FastAPI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Paso de depuración: Verificar el contenido del directorio
      - name: List directory contents
        run: |
          ls -la  # Lista los archivos del directorio
          cat main.py  # Muestra el contenido de main.py (si existe)

      # Configura Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Instalar dependencias
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      # Ejecutar FastAPI con uvicorn
      - name: Run FastAPI
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8080  # Cambia 'main' si tu archivo es diferente

      # Subir artefactos si es necesario
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fastapi-artifacts
          path: ./  # Ruta de artefactos generados
